- name: create an ec2 instance
  hosts: local
  connection: local
  # when we have aws modules we should not write the become: true
  vars:
    ami_id: "ami-0220d79f3f480ecf5"
    sg_id: "sg-032ba9da30e4b33fa"
    hosted_zone_id: "Z0971643FE7HKS61G2W9"
    domain: "vijayaws.fun"
    instances:
      - mongodb
      - redis
      - rabbitmq
      - mysql
      - catalogue
      - user
      - cart
      - shipping
      - payment
      - frontend
  tasks:
  - name: create ec2
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      region: us-east-1
    register: ec2_output
    loop: "{{ instances }}"

  - name: echo ec2_output
    debug:
      msg: " {{ ec2_output }} "
  
  - name: route53_update for backend and db
    amazon.aws.route53:
      state: present
      zone: "{{ domain }}"
      record: "{{ item }}.{{ domain }}"
      type: A
      ttl: 1
      overwrite: true
      value: "{{ ec2_output.results[ansible_loop.index0].instances[0].public_ip_address }}"
    when: item != 'frontend'
    loop: "{{ instances }}"
      
  - name: route53_update for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ domain }}"
      record: "{{ item }}.{{ domain }}"
      type: A
      ttl: 1
      overwrite: true
      value: "{{ ec2_output.results[ansible_loop.index0].instances[0].private_ip_address }}"
    when: item == 'frontend'
    loop: "{{ instances }}"